# 이 설정 파일이 없으면 기본값을 사용합니다.
# 환경변수 CONFIG_FILE로 다른 경로를 지정할 수 있습니다.

bind_host: "192.168.0.40"
bind_port: 50000
buffer_size: 32768
timeout_ms: 60000   # 60초
ssl_dir: "ssl"
worker_threads: null  # null - 시스템 코어 수만큼 사용
tls_verify_certificate: true  # TLS 인증서 검증 활성화/비활성화
disable_verify_internal_ip: true  # 내부 IP에 대한 인증서 검증 비활성화 여부
blocked_domains: []
blocked_patterns: []
trusted_certificates: []
cache_enabled: true
cache_size: 1000    # 최대 캐시 항목 수
cache_ttl_seconds: 300  # 캐시 항목 유효 시간



