[package]
name = "udss-proxy-tls"
version = "0.1.0"
edition = "2024"

[dependencies]
udss-proxy-config = { workspace = true }
udss-proxy-error = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
once_cell = { workspace = true }
rcgen = { workspace = true }