[build]
rustc-wrapper = "sccache"
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "debuginfo=0",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
    "-Z", "threads=8"
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-arg=-Wl,--as-needed",
    "-C", "link-arg=-Wl,-z,relro,-z,now",
    "-C", "force-frame-pointers=no"
]

[profile.dev]
opt-level = 1
codegen-units = 16
incremental = true
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
debug = false
incremental = false

[profile.bench]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
debug-assertions = false
overflow-checks = false

[profile.profiling]
inherits = "release"
debug = true
debug-assertions = false
strip = false
